name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REACT_APP_PFX_WASM_HOST: "/"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.100-rc.2.22477.23
    - name: Restore WASM dependencies
      run: dotnet restore PowerFxWasm
    - name: Build WASM
      run: dotnet build PowerFxWasm --no-restore  --configuration Release
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Restore Frontend Dependencies
      run: npm install
      working-directory: ./Frontend
    - name: Build React
      run: npm run build
      working-directory: ./Frontend
    - name: Copy WASM output to React
      run: cp -R ./PowerFxWasm/bin/Release/net7.0/wwwroot/* ./Frontend/build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ../Frontend/build
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
